# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5jM4saK8ZA4AQjK2RI-riHT7ga09XsC
"""

from collections import Counter
import math


class NGramModel:

    def __init__(self, n=5, alpha=1.0):
        """
        Create an N-gram model.

        n = number of words in each N-gram
        alpha = smoothing parameter
        """

        self.n = n
        self.alpha = alpha

        # Counts of complete N-grams
        self.ngram_counts = Counter()

        # Counts of contexts (first n-1 words)
        self.context_counts = Counter()

        # Set of unique words
        self.vocabulary = set()

    def create_ngrams(self, words):
        """
        Create consecutive N-grams.

        Example for n = 3:

        ["i", "like", "math", "and"]

        becomes:

        ("i", "like", "math")
        ("like", "math", "and")
        """

        ngrams = []

        for i in range(len(words) - self.n + 1):
            ngram = tuple(words[i:i + self.n])
            ngrams.append(ngram)

        return ngrams

    def fit(self, words):
        """
        Learn N-gram frequencies from the training data.
        """

        self.vocabulary = set(words)

        ngrams = self.create_ngrams(words)

        for ngram in ngrams:

            # First n-1 words
            context = ngram[:-1]

            # Last word
            next_word = ngram[-1]

            # Count complete N-gram
            self.ngram_counts[ngram] += 1

            # Count context
            self.context_counts[context] += 1

    def probability(self, context, word):
        """
        Calculate smoothed probability:

        P(word | context)

        Formula:

        P(w | c) =
        (C(c,w) + alpha)
        -----------------
        (C(c) + alpha * |V|)
        """

        context = tuple(context)

        # Complete N-gram
        ngram = context + (word,)

        # Count of complete N-gram
        ngram_count = self.ngram_counts.get(
            ngram,
            0
        )

        # Count of context
        context_count = self.context_counts.get(
            context,
            0
        )

        # Vocabulary size
        vocabulary_size = len(self.vocabulary)

        # Add-alpha smoothing
        probability = (
            ngram_count + self.alpha
        ) / (
            context_count
            + self.alpha * vocabulary_size
        )

        return probability

    def log_probability(self, context, word):
        """
        Calculate log probability.

        log(P(word | context))
        """

        probability = self.probability(
            context,
            word
        )

        return math.log(probability)

    def predict(self, context, k=5):
        """
        Return the k most probable next words.
        """

        predictions = []

        for word in self.vocabulary:

            probability = self.probability(
                context,
                word
            )

            predictions.append(
                (word, probability)
            )

        # Highest probability first
        predictions.sort(
            key=lambda x: x[1],
            reverse=True
        )

        return predictions[:k]

    def predict_next(self, context):
        """
        Return only the most probable next word.
        """

        predictions = self.predict(
            context,
            k=1
        )

        if not predictions:
            return None

        return predictions[0][0]

    def calculate_accuracy(self, test_words):
        """
        Calculate Top-1 prediction accuracy
        on a test sequence.
        """

        correct = 0
        total = 0

        for i in range(
            self.n - 1,
            len(test_words)
        ):

            # Previous n-1 words
            context = tuple(
                test_words[
                    i - self.n + 1:i
                ]
            )

            # Actual next word
            actual_word = test_words[i]

            # Model prediction
            predicted_word = self.predict_next(
                context
            )

            if predicted_word == actual_word:
                correct += 1

            total += 1

        if total == 0:
            return 0

        return correct / total

    def calculate_perplexity(self, test_words):
        """
        Calculate perplexity on test data.

        PP =
        exp(
            - average log probability
        )
        """

        log_probability_sum = 0
        total = 0

        for i in range(
            self.n - 1,
            len(test_words)
        ):

            context = tuple(
                test_words[
                    i - self.n + 1:i
                ]
            )

            actual_word = test_words[i]

            log_p = self.log_probability(
                context,
                actual_word
            )

            log_probability_sum += log_p
            total += 1

        if total == 0:
            return float("inf")

        average_log_probability = (
            log_probability_sum / total
        )

        perplexity = math.exp(
            -average_log_probability
        )

        return perplexity













