# -*- coding: utf-8 -*-
"""Thought1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bbd191m6R6ribJnhL7Lp0FALf8Vzp7EU
"""

import os

# Create the 'data' directory if it doesn't exist
if not os.path.exists('data'):
    os.makedirs('data')

# Define the content for training.txt
training_data_content = """
I like programming.
I like mathematics.
I like probability.
I want to learn programming.
I want to learn probability.
I want to learn mathematics.
I enjoy programming.
I enjoy learning.
I enjoy mathematics.
Programming is interesting.
Probability is useful.
Mathematics is useful.
I enjoy learning programming.
I enjoy learning probability.
"""

# Write the content to data/training.txt
with open('data/training.txt', 'w', encoding='utf-8') as f:
    f.write(training_data_content)

from collections import Counter
import re


def load_text(filename):
    """Load text from the training corpus."""
    with open(filename, "r", encoding="utf-8") as file:
        return file.read()


def tokenize(text):
    """
    Convert text into lowercase word tokens.
    Punctuation is removed.
    """
    return re.findall(r"\b[a-zA-Z']+\b", text.lower())


def calculate_word_probabilities(words):
    """
    Calculate the probability of each word.

    P(W = w) = Count(w) / N
    """
    word_counts = Counter(words)
    total_words = len(words)

    probabilities = {
        word: count / total_words
        for word, count in word_counts.items()
    }

    return word_counts, probabilities


def main():
    filename = "data/training.txt"

    # Load training corpus
    text = load_text(filename)

    # Tokenize corpus
    words = tokenize(text)

    # Calculate frequencies and probabilities
    word_counts, probabilities = calculate_word_probabilities(words)

    print("=== Probability-Based Word Predictor ===")
    print()

    print("Total number of words:", len(words))
    print("Vocabulary size:", len(word_counts))
    print()

    print("Word Frequencies:")
    for word, count in word_counts.most_common():
        print(f"{word:15} {count}")

    print()
    print("Word Probability Distribution:")

    for word, probability in probabilities.items():
        print(f"{word:15} {probability:.4f}")

    print()
    print("Sum of probabilities:")
    print(f"{sum(probabilities.values()):.4f}")


if __name__ == "__main__":
    main()



def create_bigrams(words):
    """Create consecutive word pairs."""
    bigrams = []

    for i in range(len(words) - 1):
        bigrams.append((words[i], words[i + 1]))

    return bigrams

def count_bigrams(bigrams):
    """Count how frequently each bigram occurs."""
    return Counter(bigrams)

def bigram_probabilities(bigram_counts):
    """Calculate P(next_word | current_word)."""

    context_counts = Counter()

    for (current_word, next_word), count in bigram_counts.items():
        context_counts[current_word] += count

    probabilities = {}

    for (current_word, next_word), count in bigram_counts.items():
        probabilities[(current_word, next_word)] = (
            count / context_counts[current_word]
        )

    return probabilities

def predict_next_word(current_word, probabilities):
    """Predict the most probable next word."""

    candidates = {
        next_word: probability
        for (word, next_word), probability in probabilities.items()
        if word == current_word
    }

    if not candidates:
        return None

    return max(candidates, key=candidates.get)





































